<form action='#' method="post">
	<label>
		<input type="text" placeholder="Login" required name="user['login']">
	</label>
    <br>
	<label>
	<input type="password" required placeholder="Password" name="user['password']">
	</label>
	<br>
	<div>
		<a href="/user/register">Registration</a> <a href="/user/restore">Forget password?</a>
	</div>
	<button type="submit" name="submit">Log in</button>
</form>