<form action='#' method="post">
    <div>
		<?php if(isset($result['error']['status_register'])):?>
			<?= $result['error']['status_register']?>
		<?php endif;?>
        <label>
            <input type="text" placeholder="Login" required name="user[login]" value="<?= htmlspecialchars($result['user']['login'] ?? '')?>">
        </label>
		<?php if(isset($result['error']['login'])):?>
            <?= $result['error']['login']?>
		<?php endif;?>
    </div>
    <div>
        <label>
            <input type="password" required placeholder="Password" name="user[password]">
        </label>
        <?php if(isset($result['error']['password'])):?>
			<?= $result['error']['password'] ?>
        <?php endif;?>
    </div>
	<div>
		<a href="/user/register">Registration</a> <a href="/user/restore">Forget password?</a>
	</div>
	<button type="submit" name="submit">Log in</button>
</form>