<form action="#" method="post">
	<div>
		<label>
			<input name="user[login]" type="text" required maxlength="20" placeholder="Login" title="20 characters maximum">
		</label>
	</div>
	<div>
		<label>
			<input name="user[email]" type="email" required maxlength="255" placeholder="Email">
		</label>
	</div>
	<div>
		<label>
			<input name="user[password]" type="password" maxlength="255" required placeholder="Password">
		</label>
	</div>
	<div>
		<label>
			<input name="user[confirm]" type="password" required placeholder="Confirm password" >
		</label>
	</div>
	<button name="submit" type="submit">Ok</button>
</form>