<form action="#" method="post">
	<div>
		<label>
			<input name="user[login]" type="text" required maxlength="20" placeholder="Login" value="<?= htmlspecialchars($result['user']['login'] ?? '')?>">
		</label>
        <?php if(isset($result['error']['login'])): ?>
		<?= htmlspecialchars($result['error']['login']) ?>
		<?php endif;?>
	</div>
	<div>
		<label>
			<input name="user[email]" type="email" required maxlength="255" placeholder="Email" value="<?= htmlspecialchars($result['user']['email'] ?? '')?>">
		</label>
		<?php if(isset($result['error']['email'])): ?>
			<?= htmlspecialchars($result['error']['email']) ?>
		<?php endif;?>
	</div>
	<div>
		<label>
			<input name="user[password]" type="password" maxlength="255" required placeholder="Password">
		</label>
		<?php if(isset($result['error']['password'])): ?>
			<?= htmlspecialchars($result['error']['password']) ?>
		<?php endif;?>
	</div>
	<div>
		<label>
			<input name="user[confirm]" type="password" required placeholder="Confirm password">
		</label>
		<?php if(isset($result['error']['confirm'])): ?>
			<?= htmlspecialchars($result['error']['confirm']) ?>
		<?php endif;?>
	</div>
	<button name="submit" type="submit">Ok</button>
</form>