<!doctype html>
<html>
<head>
	<title>WebRTC: Still photo capture demo</title>
	<meta charset='utf-8'>
<!--    <link rel="stylesheet" href="main.css" type="text/css" media="all">-->
	<script src="../../../public/js/capture.js">
	</script>
</head>
<body>
<div>
	<div class="camera">
		<video id="video">Video stream not available.</video>
		<button id="makebutton">Take photo</button>
	</div>
	<canvas id="canvas">
	</canvas>
    <div>
        <img id="photo">
    </div>
</div>
</body>
</html>