<!doctype html>
<html>
<head>
	<title>WebRTC: Still photo capture demo</title>
	<meta charset='utf-8'>
<!--    <link rel="stylesheet" href="main.css" type="text/css" media="all">-->

</head>
<body>
<div>
    <form action="/photo/save" enctype="multipart/form-data" method="POST">
        <input type="file" name="photo">
        <button type="submit" name="save" >Загрузить</button>
    </form>
</div>
<div>
    <button id="createphoto">Включить камеру</button>
</div>
<div>
	<div class="camera">
		<video id="video">Video stream not available.</video>
		<button id="makebutton">Make photo</button>
	</div>
	<canvas id="canvas">
	</canvas>
    <div>
        <img id="photo">
    </div>
</div>
<script src="../../../public/js/capture.js">
</script>
</body>
</html>